# Generated by Django 4.2 on 2023-04-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='team2',
        ),
        migrations.AlterField(
            model_name='games',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teams'),
        ),
    ]
