# Generated by Django 4.2 on 2023-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_teams_remove_games_team2_alter_games_team1'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='team2',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
