# Generated by Django 4.2 on 2023-04-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_games_team2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
