# Generated by Django 4.2 on 2023-04-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_coach_user_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='practice',
            field=models.BooleanField(default=False),
        ),
    ]
